nblog2/urls.py
from django.urls import path
from . import views

app_name = 'nblog2'

urlpatterns = [
    path('', views.NoteList.as_view(), name='note_list'),
    path('private/', views.PrivateNoteList.as_view(), name='private_note_list'),
    path('detail/<int:pk>/', views.NoteDetail.as_view(), name='note_detail'),
]

nblog2/models.py
from django.db import models
from django.utils import timezone


class Category(models.Model):
    name = models.CharField('カテゴリ名', max_length=100)

    def __str__(self):
        if hasattr(self, 'note_count'):
            return f'{self.name}({self.note_count})'
        return self.name


class Note(models.Model):
    title = models.CharField('タイトル', max_length=100)
    thumbnail = models.ImageField('サムネイル')
    category = models.ForeignKey(Category, on_delete=models.PROTECT, verbose_name='カテゴリ')
    text = models.TextField('本文', blank=True)
    is_public = models.BooleanField('公開可能か?', default=True)
    created_at = models.DateTimeField('作成日', default=timezone.now)
    updated_at = models.DateTimeField('更新日', default=timezone.now)

    def __str__(self):
        return self.title

nblog2/forms.py
from django import forms
from django.db.models import Count
from .models import Category, Note


class NoteSearchForm(forms.Form):
    """検索フォーム"""
    key_word = forms.CharField(
        label='キーワード',
        required=False,
        widget=forms.TextInput(attrs={'placeholder': '検索キーワード'})
    )

    category = forms.ModelChoiceField(
        label='カテゴリ',
        required=False,
        queryset=Category.objects.annotate(note_count=Count('note')).order_by('name'),
        widget=forms.RadioSelect,
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        all_note_count = Note.objects.filter(is_public=True).count()
        self.fields['category'].empty_label = f'全カテゴリ({all_note_count})'

nblog2/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import Http404
from django.views import generic
from .forms import NoteSearchForm
from .models import Note


class NoteList(generic.ListView):
    model = Note
    queryset = Note.objects.filter(is_public=True)
    paginate_by = 12
    ordering = '-created_at'

    def get_queryset(self):
        self.category = self.key_word = ''
        queryset = super().get_queryset()
        form = self.form = NoteSearchForm(self.request.GET or None)
        if form.is_valid():
            category = self.category = form.cleaned_data.get('category')
            if category:
                queryset = queryset.filter(category=category)

            key_word = self.key_word = form.cleaned_data['key_word']
            if key_word:
                queryset = queryset.filter(Q(title__icontains=key_word) | Q(text__icontains=key_word)).distinct()

        return queryset.select_related('category')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        heading = ''
        if self.category:
            heading += '「{}」'.format(self.category.name)
        if self.key_word:
            heading += '「{}」'.format(self.key_word)
        if heading:
            heading += 'の検索結果'
        else:
            heading = '全てのノート'
        context['heading'] = heading
        context['search_form'] = self.form
        return context


class PrivateNoteList(LoginRequiredMixin, NoteList):
    queryset = Note.objects.filter(is_public=False)
    raise_exception = True


class NoteDetail(generic.DetailView):
    model = Note

    def get_object(self, queryset=None):
        note = super().get_object()
        if note.is_public or self.request.user.is_authenticated:
            return note
        else:
            raise Http404

nblog2/templates/nblog2/base.html
{% load static %}
{% load nblog2 %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>{% block meta_title %}{% endblock %}</title>
    <meta name="description" content="{% block meta_description %}{% endblock %}">
    <link rel="stylesheet" href="{% static 'nblog2/style.css' %}">
    <link rel="stylesheet" href="https://use.typekit.net/vrt4lod.css">
    <script>
        (function (d) {
            var config = {
                    kitId: 'jjv2htu',
                    scriptTimeout: 3000,
                    async: true
                },
                h = d.documentElement, t = setTimeout(function () {
                    h.className = h.className.replace(/\bwf-loading\b/g, "") + " wf-inactive";
                }, config.scriptTimeout), tk = d.createElement("script"), f = false,
                s = d.getElementsByTagName("script")[0], a;
            h.className += " wf-loading";
            tk.src = 'https://use.typekit.net/' + config.kitId + '.js';
            tk.async = true;
            tk.onload = tk.onreadystatechange = function () {
                a = this.readyState;
                if (f || a && a != "complete" && a != "loaded") return;
                f = true;
                clearTimeout(t);
                try {
                    Typekit.load(config)
                } catch (e) {
                }
            };
            s.parentNode.insertBefore(tk, s)
        })(document);
    </script>
    {% block extrahead %}{% endblock %}
</head>
<body>

<header id="site-header" class="container">
    <h1><a href="{% url 'nblog2:note_list' %}">{% block title %}DESIGN NOTE{% endblock %}</a></h1>
</header>

{% block content %}{% endblock %}

<footer id="site-footer">
    <div class="container">
        <ul id="footer-link">
            {% block link %}{% endblock %}
        </ul>
        <p>{% block copyright %}{% endblock %}</p>
    </div>
</footer>

</body>
</html>

nblog2/templates/nblog2/base_site.html
{% extends 'nblog2/base.html' %}

{% block meta_title %}Title{% endblock %}
{% block meta_description %}サイトの説明{% endblock %}

{% block title %}PAGE TITLE{% endblock %}

{% block copyright %}© 2019 Hello World{% endblock %}
{% block link %}
    <li><a href="#">リンクA</a></li>
    <li><a href="#">リンクB</a></li>
    <li><a href="#">リンクC</a></li>
{% endblock %}

nblog2/templates/nblog2/note_detail.html
{% extends 'nblog2/base_site.html' %}
{% load humanize %}
{% load nblog2 %}

{% block meta_title %}{{ note.title }} | {{ block.super }}{% endblock %}

{% block content %}
    <div id="menu">
        <a href="{% get_return_link request %}">戻る</a>
    </div>

    <article class="container" id="detail">
        <a href="{{ note.thumbnail.url }}" target="_blank">
            <img src="{{ note.thumbnail.url }}" alt="{{ note.title }}">
        </a>
        <div id="detail-container">

            <h1 class="title">{{ note.title }}</h1>

            <div class="meta">
                <p class="category">{{ note.category }}</p>
                <p class="date">{{ note.created_at }}（
                    <time class="updated_at"
                          datetime="{{ note.updated_at | date:'Y-m-d' }}">{{ note.updated_at | naturaltime }}に更新
                    </time>
                    ）
                </p>
            </div>


            <div class="text" id="toc-start">
                {{ note.text | markdown_to_html }}
            </div>

        </div>

        <nav id="note-nav">
            <a href="#toc-start">return</a>
        </nav>
    </article>


{% endblock %}

nblog2/templates/nblog2/note_list.html
{% extends 'nblog2/base_site.html' %}
{% load humanize %}
{% load nblog2 %}

{% block content %}
    <div id="menu">
        <h1 class="container">{{ heading }}</h1>
    </div>
    <section id="list" class="container">
        {% for note in note_list %}
            <a class="box" href="{% url 'nblog2:note_detail' note.pk %}">
                <article class="box-inner">

                    <img class="thumbnail" src="{{ note.thumbnail.url }}" alt="{{ note.title }}">

                    <div class="mask">
                        <div class="caption">Read More</div>
                    </div>

                    <div class="meta">
                        <h2 class="title">{{ note.title }}</h2>

                        <p class="category">{{ note.category }}</p>
                        <p class="date">{{ note.created_at }}（
                            <time class="updated_at"
                                  datetime="{{ note.updated_at | date:'Y-m-d' }}">{{ note.updated_at | naturaltime }}に更新
                            </time>
                            ）
                        </p>
                    </div>

                </article>
            </a>
        {% empty %}
            <p class="box">検索結果はありませんでした。</p>
        {% endfor %}


        <nav id="page">
            {% for num in page_obj.paginator.page_range %}
                {% if page_obj.number == num %}
                    <span class="page current">{{ num }}</span>
                {% else %}
                    <a href="?{% url_replace request 'page' num %}" class="page">{{ num }}</a>
                {% endif %}

            {% endfor %}
        </nav>
    </section>

    <aside id="search" class="container">
        <h2>Search</h2>
        <form action="" method="GET" id="search-form">
            {{ search_form.category }}

            <div class="field">
                {{ search_form.key_word }}
            </div>

            <div class="field">
                <button type="submit">送信</button>
            </div>
        </form>
    </aside>

{% endblock %}